apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-wms
  name: locust-wms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-wms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locust-wms
    spec:
      containers:
      - image: eduardrosert/locust-wms-test:latest
        imagePullPolicy: Always
        name: locust-wms
        env:
        #- name: WMS_ACCESS_KEY
        #  value: "myauthkey=mysecretaccesstoken"
        #- name: WEIGHT_GET_CAPABILITIES
        #  value: 1
        #- name: WEIGHT_GET_LEGEND_GRAPHIC
        #  value: 2
        #- name: WEIGHT_GET_MAP
        #  value: 10
        #- name: LOG_VERBOSE
        #  value: 1
        #- name: GET_MAP_MAX_WIDTH
        #  value: 1200
        #- name: GET_MAP_MAX_HEIGHT
        #  value: 600
        - name: LOCUSTFILE
          value: "locustfile.py"
        - name: WMS_SERVICE_URL
          value: https://ows.example.com/wms
        command: [ "locust", "-f", "$(LOCUSTFILE)", "--host", "$(WMS_SERVICE_URL)" ]
        resources: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-wms
  name: locust-wms
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: locust-wms
  type: NodePort